stages:
  - deploy

deploy to prod server:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_KEY" | tr -d '\r' | ssh-add -
    - echo "Arbeitsverzeichnis"
    - pwd
    - ssh-keyscan $DEPLOYMENT_HOST >> /Users/klaus-dieterpernak/.ssh/known_hosts
  script:
    - echo "Hello GitLab 2"
    - ls -la
    - scp Readme.md $DEPLOYMENT_USER@$DEPLOYMENT_HOST:deine-abos.de/

