stages:
  - deploy

deploy branch payment:
  stage: deploy
  before_script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOYMENT_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ls -la
    - ssh-keyscan $DEPLOYMENT_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Deploy to IONOS"
    - ls -la
    - echo "LS"
    - ls *
    - scp -r * $DEPLOYMENT_USER@$DEPLOYMENT_HOST:deine-abos.de/


