# Beginn Routing
index:
    path: /
    controller: App\Controller\HomeController::index

listPaymentTypes:
    methods: GET
    path: /paymentTypes
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    methods: POST
    path: /paymentType
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    methods: GET
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    methods: PUT
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    methods: DELETE
    path: /paymentType
    controller: App\Controller\PaymentTypeController::delete

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
