# Beginn Routing
index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    methods: GET
    path: /subscriptions
    controller: App\Controller\SubscriptionsController::list

addSubscription:
    methods: POST
    path: /subscription
    controller: App\Controller\SubscriptionsController::add

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
