# Beginn Routing
index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    methods: GET
    path: /subscriptions
    controller: App\Controller\SubscriptionsController::list

newSubscription:
    methods: [GET, POST]
    path: /subscription/new
    controller: App\Controller\SubscriptionsController::new

readSubscription:
    methods: GET
    path: /subscription/{id}
    controller: App\Controller\SubscriptionsController::read

updateSubscription:
    methods: PUT
    path: /subscription/{id}
    controller: App\Controller\SubscriptionsController::update

listPaymentTypes:
    methods: GET
    path: /paymentTypes
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    methods: POST
    path: /paymentType
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    methods: GET
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    methods: PUT
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    methods: DELETE
    path: /paymentType
    controller: App\Controller\PaymentTypeController::delete

listProducts:
    methods: GET
    path: /products
    controller: App\Controller\ProductController::list

createProduct:
    methods: POST
    path: /product
    controller: App\Controller\ProductController::create

readProduct:
    methods: GET
    path: /product/{id}
    controller: App\Controller\ProductController::read

updateProduct:
    methods: PUT
    path: /product
    controller: App\Controller\ProductController::update

deleteProduct:
    methods: DELETE
    path: /product
    controller: App\Controller\ProductController::delete

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
