# Beginn Routing
index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    methods: GET
    path: /subscriptions
    controller: App\Controller\SubscriptionsController::list

newSubscription:
    methods: [GET, POST]
    path: /subscription/new
    controller: App\Controller\SubscriptionsController::new

detailSubscription:
    methods: [GET, POST]
    path: /subscription/{id}
    controller: App\Controller\SubscriptionsController::detail

updateSubscription:
    methods: PUT
    path: /subscription/{id}
    controller: App\Controller\SubscriptionsController::update

listPaymentTypes:
    methods: GET
    path: /paymentTypes
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    methods: POST
    path: /paymentType
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    methods: GET
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    methods: PUT
    path: /paymentType/{id}
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    methods: DELETE
    path: /paymentType
    controller: App\Controller\PaymentTypeController::delete

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
